### ISSUE TITLE
Daydream controller is 3DoF, not 6DoF

### ISSUE THREAD

**Issue by Tossrock** [MicrosoftDocs/webvr#27]
The Daydream controller is a 3DoF (rotation only), not a 6DoF device, as listed in the table.

Otherwise, this documentation is very useful, and I appreciate that MSDN has made it available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 392b83ea-8977-cf6c-76a6-a6ca8105b401
* Version Independent ID: 3f1209e5-b5b2-369c-93c8-d4fc5ddee2f2
* Content: [WebVR Developers Guide - WebVR](https://docs.microsoft.com/en-us/microsoft-edge/webvr/webvr_all_the_things)
* Content Source: [webvr-docs/webvr_all_the_things.md](https://github.com/MicrosoftDocs/webvr/blob/live/webvr-docs/webvr_all_the_things.md)
* Product: **microsoftedge**
* GitHub Login: @mattwojo

**Comment by mattwojo** [comment]
Just merged @Tomires update. Thank you for bringing this to our attention @Tossrock -- closing.
