### ISSUE TITLE
webView.Navigate requires System.Uri

### ISSUE THREAD

**Issue by FiddleBe** [MicrosoftDocs/webvr#31]
the webView.Navigate method expects a system.Uri parameter instead of a string.

On top of that, I tried this example, but it informs me that "your browser does not support WebVR"
None theless, I'm already at windows 10 1809 and min version and target version are both 1809.
Since Webvr is supposed to be supported as of 1803, I think something is missing in the doco?

Also tested with target version and min version 1803: to no avail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a49bea2d-92e8-7255-90d0-9084f0b72db6
* Version Independent ID: 15959a58-ac6f-1ddb-f233-a5a155a08ac4
* Content: [WebVR in WebView - WebVR](https://docs.microsoft.com/en-us/microsoft-edge/webvr/webvr-in-webview)
* Content Source: [webvr-docs/webvr-in-webview.md](https://github.com/MicrosoftDocs/webvr/blob/live/webvr-docs/webvr-in-webview.md)
* Product: **microsoft-edge**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by mattwojo** [comment]
Yes - it is true that WebVR is no longer supported. WebVR has been replaced by the WebXR standard: https://www.w3.org/TR/webxr/. Appologies for the delay in updating these docs. They have been moved into "archive" status with a deprecation message added.
https://caniuse.com/?search=webxr
