### ISSUE TITLE
Compatibility with the new Microsoft Edge

### ISSUE THREAD

**Issue by jm-trd-ms** [MicrosoftDocs/webvr#38]
Are there plans to update the documentation to address Microsoft Edge \(Chromium\)?  
This documentation is currently linked from the [Microsoft Edge MicrosoftDocs](https://docs.microsoft.com/microsoft-edge).

**Comment by mattwojo** [comment]
WebVR has been replaced by the WebXR standard: https://www.w3.org/TR/webxr/. WebVR is no longer supported. I believe there is a work item open for someone to author some WebXR docs, but behavior on Microsoft Edge (Chromium) should align with any other Chromium performance in regard to WebXR to my knowledge. https://caniuse.com/?search=webxr
