### ISSUE TITLE
WebVR in Edge samples broken, perhaps WebVR support entirely broken

### ISSUE THREAD

**Issue by berndverst** [MicrosoftDocs/webvr#39]
All WebVR Samples freeze after 1-2 seconds in Edge Version 87.0.664.75 (Official build) (64-bit)

Clicking the VR button in the sample does not load anything in WMR HMD (in my case HP Reverb G2)

It seems the current version of Edge no longer supports WebVR properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98bf4e20-1926-2945-82a4-9113a0f541f9
* Version Independent ID: 85dc9a8d-2b97-4632-e046-a2fddbffe218
* Content: [WebVR with Microsoft Edge - WebVR](https://docs.microsoft.com/en-us/microsoft-edge/webvr/webvr-with-edge)
* Content Source: [webvr-docs/webvr-with-edge.md](https://github.com/MicrosoftDocs/webvr/blob/live/webvr-docs/webvr-with-edge.md)
* Product: **microsoft-edge**
* Technology: **webvr**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Yes - this is true. WebVR has been replaced by the WebXR standard: https://www.w3.org/TR/webxr/. WebVR is no longer supported.
